#############################################################################
# Makefile for building: gt
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  gt.pro
# Template: subdirs
# Command: C:\work\private\Qt\5.3\mingw482_32\bin\qmake.exe -spec win32-g++ -o Makefile gt.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\work\private\Qt\5.3\mingw482_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-GtCore \
		sub-GtLib \
		sub-GtGui \
		sub-Grepotool


sub-GtCore-qmake_all:  FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile
	cd GtCore\ && $(MAKE) -f Makefile qmake_all
sub-GtCore: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-GtCore-make_first: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GtCore-all: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GtCore-clean: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GtCore-distclean: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GtCore-install_subtargets: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GtCore-uninstall_subtargets: FORCE
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-GtLib-qmake_all:  FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile
	cd GtLib\ && $(MAKE) -f Makefile qmake_all
sub-GtLib: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-GtLib-make_first: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GtLib-all: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GtLib-clean: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GtLib-distclean: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GtLib-install_subtargets: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GtLib-uninstall_subtargets: FORCE
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-GtGui-qmake_all:  FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile
	cd GtGui\ && $(MAKE) -f Makefile qmake_all
sub-GtGui: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-GtGui-make_first: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-GtGui-all: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-GtGui-clean: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-GtGui-distclean: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-GtGui-install_subtargets: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-GtGui-uninstall_subtargets: FORCE
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Grepotool-qmake_all:  FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile
	cd Grepotool\ && $(MAKE) -f Makefile qmake_all
sub-Grepotool: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile
sub-Grepotool-make_first: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile 
sub-Grepotool-all: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile all
sub-Grepotool-clean: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile clean
sub-Grepotool-distclean: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Grepotool-install_subtargets: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile install
sub-Grepotool-uninstall_subtargets: FORCE
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: gt.pro ../../Qt/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf ../../Qt/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		../../Qt/5.3/mingw482_32/mkspecs/qdevice.pri \
		../../Qt/5.3/mingw482_32/mkspecs/features/device_config.prf \
		../../Qt/5.3/mingw482_32/mkspecs/common/shell-win32.conf \
		../../Qt/5.3/mingw482_32/mkspecs/qconfig.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		../../Qt/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		../../Qt/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/default_post.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/yacc.prf \
		../../Qt/5.3/mingw482_32/mkspecs/features/lex.prf \
		gt.pro
	$(QMAKE) -spec win32-g++ -o Makefile gt.pro
..\..\Qt\5.3\mingw482_32\mkspecs\features\spec_pre.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\qdevice.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\features\device_config.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\common\shell-win32.conf:
..\..\Qt\5.3\mingw482_32\mkspecs\qconfig.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_designer.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_designer_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_help.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_help_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\5.3\mingw482_32\mkspecs\features\qt_functions.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\qt_config.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\win32\qt_config.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\win32-g++\qmake.conf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\spec_post.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\exclusive_builds.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\default_pre.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\win32\default_pre.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\resolve_config.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\exclusive_builds_post.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\default_post.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\win32\rtti.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\precompile_header.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\warn_on.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\win32\windows.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\testcase_targets.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\exceptions.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\yacc.prf:
..\..\Qt\5.3\mingw482_32\mkspecs\features\lex.prf:
gt.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ -o Makefile gt.pro

qmake_all: sub-GtCore-qmake_all sub-GtLib-qmake_all sub-GtGui-qmake_all sub-Grepotool-qmake_all FORCE

make_first: sub-GtCore-make_first sub-GtLib-make_first sub-GtGui-make_first sub-Grepotool-make_first FORCE
all: sub-GtCore-all sub-GtLib-all sub-GtGui-all sub-Grepotool-all FORCE
clean: sub-GtCore-clean sub-GtLib-clean sub-GtGui-clean sub-Grepotool-clean FORCE
distclean: sub-GtCore-distclean sub-GtLib-distclean sub-GtGui-distclean sub-Grepotool-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-GtCore-install_subtargets sub-GtLib-install_subtargets sub-GtGui-install_subtargets sub-Grepotool-install_subtargets FORCE
uninstall_subtargets: sub-GtCore-uninstall_subtargets sub-GtLib-uninstall_subtargets sub-GtGui-uninstall_subtargets sub-Grepotool-uninstall_subtargets FORCE

sub-GtCore-debug:
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
sub-GtLib-debug:
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
sub-GtGui-debug:
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
sub-Grepotool-debug:
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-GtCore-debug sub-GtLib-debug sub-GtGui-debug sub-Grepotool-debug

sub-GtCore-release:
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
sub-GtLib-release:
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
sub-GtGui-release:
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
sub-Grepotool-release:
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile release
release: sub-GtCore-release sub-GtLib-release sub-GtGui-release sub-Grepotool-release

sub-GtCore-check:
	@if not exist GtCore\ mkdir GtCore\ & if not exist GtCore\ exit 1
	cd GtCore\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtCore\GtCore.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
sub-GtLib-check:
	@if not exist GtLib\ mkdir GtLib\ & if not exist GtLib\ exit 1
	cd GtLib\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtLib\GtLib.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
sub-GtGui-check:
	@if not exist GtGui\ mkdir GtGui\ & if not exist GtGui\ exit 1
	cd GtGui\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\GtGui\GtGui.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
sub-Grepotool-check:
	@if not exist Grepotool\ mkdir Grepotool\ & if not exist Grepotool\ exit 1
	cd Grepotool\ && ( if not exist Makefile $(QMAKE) C:\work\private\grepolis\grepotool-2.0.15-src\Grepotool\Grepotool.pro -spec win32-g++ -o Makefile ) && $(MAKE) -f Makefile check
check: sub-GtCore-check sub-GtLib-check sub-GtGui-check sub-Grepotool-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

